"""
MCP Tools - Auto-generated importable wrappers for MCP servers.

This package is automatically generated by mcp-coordinator.
DO NOT EDIT MANUALLY.

Usage:
    from graph_rlm.backend.mcp_tools import list_servers
    from graph_rlm.backend.mcp_tools.chroma import query, add_documents
"""

from typing import Any
from graph_rlm.backend.src.mcp_integration.runtime import call_mcp_tool as call_tool

# Public API
__all__ = ["call_tool", "run_skill", "list_servers"]

def run_skill(name: str, args: dict | None = None) -> Any:
    """
    Execute a skill by name.

    Args:
        name: Name of the skill to execute
        args: Arguments to pass to the skill function

    Returns:
        Result of the skill execution
    """
    import asyncio
    from graph_rlm.backend.src.mcp_integration.skill_harness import execute_skill

    try:
        asyncio.get_running_loop()
        has_running_loop = True
    except RuntimeError:
        has_running_loop = False

    if has_running_loop:
        # If we are here, there's a loop running in this thread.
        # To avoid "cannot be called from a running event loop",
        # we run in a separate thread.
        from concurrent.futures import ThreadPoolExecutor

        with ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(asyncio.run, execute_skill(name, args or {}))
            return future.result()
    else:
        # No loop in this thread, safe to use asyncio.run directly
        return asyncio.run(execute_skill(name, args or {}))

def list_servers() -> list[str]:
    """Get list of all available MCP servers."""
    return ['docker-mcp', 'brave-search', 'arxiv-mcp-server', 'wolframalpha', 'mcp-server-firecrawl', 'neo4j-mcp', 'advanced-reasoning', 'fermat-mcp', 'playwright', 'gitmcp', 'notebooklm', 'reflective-agent-architecture', 'ast-mcp-server', 'desktop-commander', 'mcp-obsidian', 'community-server-llm-txt', 'context7', 'mcp-logic', 'hybrid-ai', 'diagram-server', 'coinbase-trade-assistant', 'chatdag', 'verifier-graph', 'data-forge', 'memory', 'chroma']
