"""
MCP Tools - Auto-generated importable wrappers for MCP servers.

This package is automatically generated by mcp-coordinator.
DO NOT EDIT MANUALLY.

Usage:
    from graph_rlm.backend.mcp_tools import list_servers
    from graph_rlm.backend.mcp_tools.chroma import query, add_documents
"""

from typing import Any
from graph_rlm.backend.src.mcp_integration.runtime import call_mcp_tool as call_tool

def run_skill(name: str, args: dict | None = None) -> Any:
    """
    Execute a skill by name.

    Args:
        name: Name of the skill to execute
        args: Arguments to pass to the skill function

    Returns:
        Result of the skill execution
    """
    import asyncio
    from graph_rlm.backend.src.mcp_integration.skill_harness import execute_skill
    return asyncio.run(execute_skill(name, args or {}))

def list_servers() -> list[str]:
    """Get list of all available MCP servers."""
    return ['docker-mcp', 'brave-search', 'arxiv-mcp-server', 'wolframalpha', 'mcp-server-firecrawl', 'neo4j-mcp', 'advanced-reasoning', 'fermat-mcp', 'playwright', 'gitmcp', 'notebooklm', 'reflective-agent-architecture', 'ast-mcp-server', 'local-repl', 'desktop-commander', 'mcp-obsidian', 'community-server-llm-txt', 'context7', 'mcp-logic', 'hybrid-ai', 'diagram-server', 'coinbase-trade-assistant', 'chatdag', 'docker-hub', 'verifier-graph', 'data-forge', 'memory']
