"""
This module provides validation logic for the ModelObservability domain to detect
'Success Hallucinations'. It ensures that an agent's claim of task completion
is supported by the underlying execution logs, specifically checking for
unhandled errors in the final execution traces.
"""

import re
from typing import List, Dict, Any


def validate_fidelity_high_surprise(
    agent_output: str,
    execution_trace: List[Dict[str, Any]]
) -> bool:
    """
    Validates that an agent's success claim is not a hallucination by checking
    trace logs for TypeErrors or AttributeErrors in the final steps.

    Args:
        agent_output: The text generated by the agent containing its conclusion.
        execution_trace: A list of operation logs, each containing 'status' and
            'error_type' if available.

    Returns:
        bool: True if no success hallucination is detected, False if the agent
            claims success despite recent execution failures.
    """
    success_keywords = [
        r"task is complete",
        r"file is saved",
        r"successfully updated",
        r"operation finished",
        r"done"
    ]

    # Check if the agent is claiming success
    claims_success = any(
        re.search(pattern, agent_output, re.IGNORECASE)
        for pattern in success_keywords
    )

    if not claims_success:
        return True

    # Inspect the most recent trace entries for specific fatal errors
    critical_errors = {"TypeError", "AttributeError", "FileNotFoundError"}

    for log in reversed(execution_trace):
        # We only care about the latest functional block leading to the claim
        status = log.get("status", "success")
        error_type = log.get("error_type", "")

        if status == "failed" and error_type in critical_errors:
            return False

    return True
