import datetime
import json
import uuid
from unittest.mock import MagicMock, patch

import pytest

from graph_rlm.backend.src.core.agent import Agent


@pytest.mark.asyncio
async def test_knot_propagation_to_prompt():
    """
    Verifies that a critique generated by the Sheaf Laplacian
    propagates all the way to the Agent's system prompt.
    """
    # 1. Mock DB and LLM
    mock_db = MagicMock()
    mock_llm = MagicMock()
    mock_llm.get_embedding.return_value = [0.1] * 3072

    # 2. Setup Agent
    agent = Agent()
    agent.db = mock_db
    agent.llm = mock_llm

    # 3. Mock Sheaf Diagnosis with a Knot
    mock_critique = "TEMPORAL_CONFLICT: Planning work already finished."

    # 4. Mock Dashboard Data to return this node
    # The agent fetches: 1. SLAC reflexion node (Only 1 DB call in dashboard metrics)
    mock_db.query.side_effect = [
        # Call 1: SLAC reflexion query
        [{"at_score": 0.5, "stage": "S", "bar": "[###]", "critique": mock_critique}]
    ]

    # Setup morph_memory to provide sheaf_energy
    agent.morph_memory = MagicMock()
    mock_event = MagicMock()
    mock_event.sheaf_score = 0.85
    mock_event.omcd_score = 0.9
    mock_event.operation = MagicMock()
    mock_event.operation.value = "PROCESS"
    mock_event.metabolic_state = "STABLE"
    agent.morph_memory.all_events = [mock_event]

    # 5. Simulate dash metrics gathering
    exec_state = MagicMock()
    dashboard_data = await agent._get_dashboard_metrics(exec_state, "test_session")

    assert dashboard_data["slac_critique"] == mock_critique
    assert dashboard_data["sheaf_energy"] == "0.85"

    # 6. Verify Prompt Injection logic
    energy_val = 0.85
    system_prompt = "Base System Prompt"

    # This mirrors the logic in agent.py _initialize_step:
    if energy_val > 0.7:
        critique = dashboard_data.get("slac_critique")
        critique_str = f"\nDIAGNOSIS: {critique}" if critique else ""
        system_prompt += (
            f"\n\n--- ⚠️ TOPOLOGICAL DEFECT DETECTED (Energy: {energy_val:.2f}){critique_str} ---\n"
            "Your memory graph shows a high logical contradiction or 'knot'."
        )
        if critique:
            system_prompt += f"\nSpecifically, address this inconsistency: {critique}"

        system_prompt += "\nPass this specific diagnosis to your sub-agent to ensure targeted resolution."

    assert mock_critique in system_prompt
    assert "DIAGNOSIS" in system_prompt
    assert "Pass this specific diagnosis" in system_prompt
    print("\n[SUCCESS] Knot critique successfully injected into prompt logic.")


if __name__ == "__main__":
    import asyncio

    asyncio.run(test_knot_propagation_to_prompt())
